publisher/urls.py
from django.urls import path

from publisher import views

app_name = 'publisher'

urlpatterns = [
    path('publisher-list/', views.publisher_list, name='publisher_list'),
    path('publisher-detail/<int:id>/', views.publisher_detail, name='publisher_detail'),
    path('publisher-create/', views.publisher_create, name='publisher_create'),
    path('publisher-safe_delete/<int:id>/', views.publisher_safe_delete, name='publisher_safe_delete'),
    path('publisher-update/<int:id>/', views.publisher_update, name='publisher_update'),
    path('publisher-sale/<int:id>/', views.publisher_sale.as_view(), name='publisher_sale'),


]

schoolshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from publisher import views

urlpatterns = [
    url(r'^$', views.publisher_list),
    path('admin/', admin.site.urls),


    path('publisher/', include('publisher.urls', namespace='publisher')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    
]

# 添加图片
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('update-password/', views.change_pass, name='update_password'),



]

userprofile/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


# 用户扩展信息
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)


# 信号接收函数，每当新建 User 实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# 信号接收函数，每当更新 User 实例时自动调用
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

userprofile/forms.py
from django import forms
# 引入 User 模型
from django.contrib.auth.models import User

from userprofile.models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 修改密码
class ChangeForm(forms.Form):
    username = forms.CharField(label='用户名')
    old_password = forms.CharField(label='原密码', widget=forms.PasswordInput())
    new_password = forms.CharField(label='新密码', widget=forms.PasswordInput())


# 注册用户表单
class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from userprofile.forms import UserLoginForm, UserRegisterForm, ProfileForm, ChangeForm

# 用户登录
from userprofile.models import Profile


def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data = user_login_form.clean()
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect("publisher:publisher_list")
            else:
                return HttpResponse("账号或者密码不正确，请重新输入")
        else:
            return HttpResponse("账号或者密码输入不合法")

    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或者POST登录")


# 退出登录
def user_logout(request):
    logout(request)
    return redirect('publisher:publisher_list')


# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("publisher:publisher_list")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 用户删除
@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect('publisher:publisher_list')
        else:
            return HttpResponse("你没有删除操作的权限")
    else:
        return HttpResponse("仅接受POST请求")


# 编辑用户的信息
@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    profile = Profile.objects.get(user_id=id)
    if request.method == 'POST':
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息")
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd["avatar"]
            profile.save()
            return redirect('userprofile:edit', id=id)
        else:
            return HttpResponse("表单注册有误，请重新输入~")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = {'profile_form': profile_form, 'profile': profile, 'user': user}
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


# 修改密码
@login_required(login_url='/userprofile/login/')
def change_pass(request):
    if request.method == 'POST':
        form = ChangeForm(request.POST)
        if form.is_valid():
            username = request.user.username
            old_password = request.POST.get('old_password', '')
            # 验证用户密码是否正确
            user = authenticate(username=username, password=old_password)
            if user:
                # 获取新密码
                new_password = request.POST.get('new_password', '')
                # 设置密码
                user.set_password(new_password)
                user.save()
                return HttpResponse("修改成功!")
            else:
                return HttpResponse("用户名获取密码不正确")
        else:
            return HttpResponse("用户名或者密码不合法")
    else:
        form = ChangeForm()
        context = {'form': form}
        return render(request, 'userprofile/change.html', context)

templates/userprofile/change.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    修改密码
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-4">
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="modal-content" style="margin-top: 30%;margin-left: 100%">
                        <table>
                            <h4 class="mt-2" style="align-self: center">修改密码</h4>
                            <div class="mt-2 ml-4">
                                {{ form.as_ul }}
                            </div>
                            <button type="submit" class="btn btn-primary float-right">提交</button>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/userprofile/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    用户信息
{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%;border-radius: 15%;" class="col-md-4" alt="">
             {% else %}
                <h5 class="col-md-4">暂无头像</h5>
            {% endif %}
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {# 上传头像 #}
                <div class="form-group col-md-4">
                    <label for="avatar">上传头像</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    登录
{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-6 offset-md-3" style="margin-top: 6%;">
            <div class="modal-content">
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="alert alert-success">
                        <h3 style="text-align: center">校园小商品交易平台登录</h3>
                    </div>
                    {# 账号 #}
                    <div class="form-group">
                        <label for="username">账号:</label>
                        <input type="text" id="username" name="username" class="form-control" placeholder="请输入用户名">
                    </div>
                    {# 密码 #}
                    <div class="form-group">
                        <label for="password">密码:</label>
                        <input type="password" id="password" name="password" class="form-control" placeholder="请输入密码">
                    </div>
                    {# 提交表单 #}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <button type="submit" class="btn btn-primary">登录</button>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'userprofile:register' %}" class="btn-success btn" role="button">注册</a>
                    <br/>
                    <br/>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/userprofile/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    注册
{% endblock %}
{% block content %}
    <div class="container">
        <div class="offset-md-3 col-md-6" style="margin-top: 2%">
            <div class="modal-content">
                <form action="." method="post">
                    {% csrf_token %}
                     <div class="alert alert-success">
                        <h4 style="text-align: center" >校园小商品交易平台注册</h4>
                    </div>
                    <div class="form-group">
                        <label for="username">用户名：</label>
                        <input type="text" id="username" name="username" class="form-control" placeholder="请输入用户名" required>
                    </div>
                    <div class="form-group">
                        <label for="email">邮箱：</label>
                        <input type="text" class="form-control" id="email" name="email" placeholder="请输入邮箱" required>
                    </div>
                    <div class="form-group">
                        <label for="password">密码：</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码" required>
                    </div>
                    <div class="form-group">
                        <label for="password2">确认密码：</label>
                        <input type="password" class="form-control" id="password2" name="password2" placeholder="请确认密码" required>
                    </div>
                    <div style="text-align: center">
                        <button type="submit" class="btn btn-success" style="">注册</button>
                        <br/>
                        <br/>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}