publisher/urls.py
from django.urls import path

from publisher import views

app_name = 'publisher'

urlpatterns = [
    path('publisher-list/', views.publisher_list, name='publisher_list'),
    path('publisher-detail/<int:id>/', views.publisher_detail, name='publisher_detail'),
    path('publisher-create/', views.publisher_create, name='publisher_create'),
    path('publisher-safe_delete/<int:id>/', views.publisher_safe_delete, name='publisher_safe_delete'),
    path('publisher-update/<int:id>/', views.publisher_update, name='publisher_update'),
    path('publisher-sale/<int:id>/', views.publisher_sale.as_view(), name='publisher_sale'),


]

schoolshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from publisher import views

urlpatterns = [
    url(r'^$', views.publisher_list),
    path('admin/', admin.site.urls),


    path('publisher/', include('publisher.urls', namespace='publisher')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    
]

# 添加图片
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publisher/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.utils import timezone


class Product(models.Model):
    # 发布者,外键方式删除
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)
    # 联系方式
    phone = models.CharField(max_length=20, blank=False)
    # 图片
    avatar = models.ImageField(upload_to='images/%Y%m%d/', blank=True)
    # 商品名称
    name = models.CharField(max_length=50)
    # 商品价格
    price = models.CharField(max_length=20)
    # 商品销售量
    total_sale = models.PositiveIntegerField(default=0)
    # 商品描述
    description = models.TextField()
    # 商品的发布时间
    created = models.DateTimeField(default=timezone.now)

    # 保存图片
    def save(self, *args, **kwargs):
        images = super(Product, self).save(*args, **kwargs)
        # 缩放图片
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 350
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return images

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.name

publisher/forms.py
from django import forms

from .models import Product


class productForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'phone', 'avatar', 'price', 'description')

publisher/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from django.views.generic import ListView

from userprofile.models import Profile
from .forms import productForm
from publisher.models import Product
# 引入Q对象
from django.db.models import Q


def publisher_list(request):
    # 搜索商品
    search = request.GET.get('search')
    order = request.GET.get('order')
    if search:
        product_list = Product.objects.filter(Q(price__contains=search) | Q(name__contains=search))
        print(product_list)
    else:
        search = ''
        product_list = Product.objects.all()
    if order == 'price':
        product_list = product_list.order_by('-price')
    else:
        pass
    paginator = Paginator(product_list, 3)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    # 传递给模板的对象
    context = {'products': products, 'search': search, 'order': order}
    # 载入模板，返回给context
    return render(request, 'publisher/list.html', context)


# 详情页面
def publisher_detail(request, id):
    # 取出相应的商品
    products = Product.objects.get(id=id)
    profile = Profile.objects.all()
    # 传递给模板
    context = {'products': products, 'profile': profile}
    # 载入模板，返回给context
    return render(request, 'publisher/detail.html', context)


# 新增商品信息
@login_required(login_url='profile/login/')
def publisher_create(request):
    # 判断是否提交
    if request.method == 'POST':
        product_post_form = productForm(request.POST, request.FILES)
        if product_post_form.is_valid():
            new_product = product_post_form.save(commit=False)
            new_product.publisher = User.objects.get(id=request.user.id)
            new_product.save()
            return redirect('publisher:publisher_list')
        else:
            return HttpResponse('表单有误，重新填写')
    else:
        product_post_form = productForm()
        context = {'product_post_form': product_post_form}
        return render(request, 'publisher/create.html', context)


# 删除商品
def publisher_safe_delete(request, id):
    if request.method == 'POST':
        product = Product.objects.get(id=id)
        product.delete()
        return redirect('publisher:publisher_list')
    else:
        return HttpResponse("仅允许POST请求")


# 修改商品
def publisher_update(request, id):
    product = Product.objects.get(id=id)
    if request.method == 'POST':
        product_post_form = productForm(data=request.POST)
        if product_post_form.is_valid():
            product.name = request.POST['name']
            product.price = request.POST['price']
            product.description = request.POST['description']
            if request.FILES.get('avatar'):
                product.avatar = request.FILES.get('avatar')
            product.save()
            return redirect('publisher:publisher_detail', id=id)
        else:
            return HttpResponse("输入的表单有误，请重新输入")
    # GET提交
    else:
        product_post_form = productForm()
        context = {'products': product, 'product_post_form': product_post_form}
        return render(request, 'publisher/update.html', context)


# 出售量
class publisher_sale(View):
    def post(self, request, *args, **kwargs):
        product = Product.objects.get(id=kwargs.get('id'))
        product.total_sale += 1
        product.save()
        return HttpResponse('success')

templates/publisher/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    发布商品
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group mt-4">
                        <label for="name">商品名：</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    {# 文章标题图 #}
                    <div class="form-group">
                        <label for="avatar">图片：</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>
                    {# 联系方式 #}
                    <div class="form-group mt-4">
                        <label for="phone">联系方式：</label>
                        <input type="text" class="form-control" id="phone" name="phone">
                    </div>
                    {# 价格 #}
                    <div class="form-group">
                        <label for="price">价格：</label>
                        <input type="text" class="form-control" id="price" name="price">
                    </div>
                    {# 描述 #}
                    <div class="form-group">
                        <label for="description">描述：</label>
                        <textarea name="description" id="description" cols="30" rows="5" class="form-control"></textarea>
                    </div>
                    {# 提交按钮 #}
                    <button type="submit" class="btn btn-success float-right">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/publisher/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    商品详情
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row col-10 ml-lg-5">
            <div class="mt-4">
                <img src="{{ products.avatar.url }}" alt="" style="width: 890px; height: 450px; border-radius: 20px;">
            </div>
            <div>
                <h4 class="mt-4 col-12 mb-4">商品：{{ products.name }}</h4>
            </div>
            {# 销售量 #}
            <div style="text-align: center" class="mt-4">
                <button class="btn btn-primary" type="button" onclick="validate_is_like(
                        '{% url 'publisher:publisher_sale' products.id %}',
                        {{ products.id }},
                        {{ products.total_sale }}
                        )"
                >
                    <span>购买</span>
                </button>

                <span class="ml-2" style="color: red">销售量:</span>
                <span style="color: red" id="sale_number"> {{ products.total_sale }}</span>
            </div>

            <div class="col-12 alert alert-success">

                价格: &nbsp;<span style="color: red;font-size: x-large">约￥{{ products.price }}</span>
                {% if user == products.publisher %}
                    <a href="#" onclick="confirm_safe_delete()" class="mx-2">删除商品</a>
                    <a href="{% url 'publisher:publisher_update' products.id %}">修改信息</a>
                {% endif %}
                <div>商家：<span style="color: #005cbf;">{{ products.publisher }}</span></div>
                <div>联系方式：{{ products.phone }}</div>
            </div>
            <form action="{% url 'publisher:publisher_safe_delete' products.id %}"
                  id="safe_delete"
                  method="post"
                  style="display: none">
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>

            <div class="col-12">
                <p>{{ products.description }}</p>
            </div>
        </div>
        <br>
        <br>
    </div>

    {% block script %}
        <script>
            function confirm_safe_delete() {
                layer.open({
                    title: "确认删除",
                    content: "确认删除这个商品吗？",
                    yes: function (index, layer) {
                        $('form#safe_delete button').click();
                        layer.close(index);
                    }
                })
            };
        </script>

        <script src="{% static 'csrf.js' %}"></script>
        <script>
            // 点赞功能主函数
            function validate_is_like(url, id, total_sale) {
                // 取出 LocalStorage 中的数据
                let storage = window.localStorage;
                const storage_str_data = storage.getItem("my_blog_data");
                let storage_json_data = JSON.parse(storage_str_data);
                // 若数据不存在，则创建空字典
                if (!storage_json_data) {
                    storage_json_data = {}
                }
                ;
                // 检查当前文章是否已点赞。是则 status = true


                // 用 Jquery 找到点赞数量，并 +1
                $('span#likes_number').text(total_sale + 1).css('color', '#dc3545');

                // 用 ajax 向后端发送 post 请求
                $.post(
                    url,
                    // post 只是为了做 csrf 校验，因此数据为空
                    {},
                    function (result) {
                        if (result === 'success') {
                            // 尝试修改点赞数据
                            try {
                                storage_json_data[id] = true;
                            } catch (e) {
                                window.localStorage.clear();
                            }
                            ;
                            // 将字典转换为字符串，以便存储到 LocalStorage
                            const d = JSON.stringify(storage_json_data);
                            // 尝试存储点赞数据到 LocalStorage
                            try {
                                storage.setItem("my_blog_data", d);
                            } catch (e) {
                                // code 22 错误表示 LocalStorage 空间满了
                                if (e.code === 22) {
                                    window.localStorage.clear();
                                    storage.setItem("my_blog_data", d);
                                }
                            }
                            ;
                        } else {
                            layer.msg("与服务器通信失败..过一会儿再试试呗~");
                        }

                    }
                );
            };

            $(function () {
                setInterval(function () {
                    $("#sale_number").load(location.href + " #sale_number");//注意后面DIV的ID前面的空格，很重要！没有空格的话，会出双眼皮！（也可以使用类名）
                }, 100);//8秒自动刷新
            });
        </script>

    {% endblock %}

{% endblock %}

templates/publisher/list.html
{% extends 'base.html' %}
{% load  filters_and_time %}
{% load static %}

{% block title %}
    首页
{% endblock %}
{% block content %}
    <div class="container">

    <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto mt-3">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text"
                    class="form-control mb-2 mr-sm-2 col-lg-12"
                    name="search"
                    placeholder="搜索商品..."
                    required
                >
            </form>
        </div>
    </div>

    <!-- 新增，搜索提示语 -->
    {% if search %}
        {% if products %}
            <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
            <hr>
        {% else %}
            <h4>暂无<span style="color: red">"{{ search }}"</span>有关的商品。</h4>
            <hr>
        {% endif %}
    {% endif %}

        <div class="row mt-1">
            {% for product in products %}
                <div class="col-4 mb-4">
                    <div class="card">
                        {# 图片 #}
                        {% if product.avatar %}
                            <div>
                                <img src="{{ product.avatar.url }}" alt="avatar" style="max-width: 100%;">
                            </div>
                        {% endif %}
                        {# 价格 #}
                        <span class="mt-2" style="color: red;font-size: x-large">约￥{{ product.price }}</span>
                        {# 标题 #}
                        <span style="color: #005cbf">{{ product.name }}</span>
                        {# 发布者 #}
                        <span style="color: gray;">发布人：{{ product.publisher }}</span>
                        {# 注脚 #}
                        <div class="card-footer">
                            <span>
                                <i class="fas fa-clock" style="color: pink;"></i>
                                     {{ product.created|timesince_zh}}
                            </span>
                            <span class="ml-4">销售量：{{ product.total_sale }}</span>
                            <a href="{% url 'publisher:publisher_detail' product.id %}"
                               class="btn btn-primary float-right">详情</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {# 页码导航 #}
        <div class="pagination row">
            <div class="m-auto">
                <span class="step-links">
                    {# 如果不是第一页就向上翻 #}
                    {% if products.has_previous %}
                        <a href="?page=1&search={{ search }}&order={{ order }}" class="btn btn-success">
                        &laquo;1
                        </a>
                        <span>...</span>
                        <a href="?page={{ products.previous_page_number }}&search={{ search }}&order={{ order }}" class="btn btn-secondary">
                        {{ products.previous_page_number }}
                        </a>
                    {% endif %}
                    {# 当前页 #}
                <span class="current btn btn-danger btn-lg">
                    {{ products.number }}
                </span>
                {# 如果不是最后一页就向下翻 #}
                    {% if products.has_next %}
                        <a href="?page={{ products.next_page_number }}&search={{ search }}" class="btn btn-secondary">
                            {{ products.next_page_number }}
                        </a>
                        <span>...</span>
                        <a href="?page={{ products.paginator.num_pages }}&search={{ search }}&order={{ order }}" class="btn btn-success">
                        {{ products.paginator.num_pages }} &laquo;
                        </a>

                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

templates/publisher/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    修改信息
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                 <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group mt-4">
                        <label for="name">商品名：</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ products.name }}">
                    </div>
                     {# 图片 #}
                     <div class="form-group">
                         <label for="avatar">图片：</label>
                         <input type="file" class="form-control-file" name="avatar" id="avatar">
                     </div>
                     {# 联系方式 #}
                    <div class="form-group mt-4">
                        <label for="phone">联系方式：</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ products.phone }}">
                    </div>
                    {# 价格 #}
                    <div class="form-group">
                        <label for="price">价格：</label>
                        <input type="text" class="form-control" id="price" name="price" value="{{ products.price }}">
                    </div>
                    {# 描述 #}
                    <div class="form-group">
                        <label for="description">描述：</label>
                        <textarea name="description" id="description" cols="30" rows="5" class="form-control">{{ products.description }}</textarea>
                    </div>
                    {# 提交按钮 #}
                    <button type="submit" class="btn btn-success float-right">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}