publisher/urls.py
from django.urls import path

from publisher import views

app_name = 'publisher'

urlpatterns = [
    path('publisher-list/', views.publisher_list, name='publisher_list'),
    path('publisher-detail/<int:id>/', views.publisher_detail, name='publisher_detail'),
    path('publisher-create/', views.publisher_create, name='publisher_create'),
    path('publisher-safe_delete/<int:id>/', views.publisher_safe_delete, name='publisher_safe_delete'),
    path('publisher-update/<int:id>/', views.publisher_update, name='publisher_update'),
    path('publisher-sale/<int:id>/', views.publisher_sale.as_view(), name='publisher_sale'),


]

schoolshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from publisher import views

urlpatterns = [
    url(r'^$', views.publisher_list),
    path('admin/', admin.site.urls),


    path('publisher/', include('publisher.urls', namespace='publisher')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    
]

# 添加图片
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('update-password/', views.change_pass, name='update_password'),



]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    {# 引入Font awesome #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
</head>
<body>
{% include 'header.html' %}
{% block content %}

{% endblock %}
{% include 'footer.html' %}
<script src="{% static 'jquery/jquery-3.5.1.js' %}"></script>
<script src="{% static 'layer/layer.js' %}"></script>
<script src="{% static 'popper/popper.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% block script %}{% endblock script %}
</body>
</html>

templates/footer.html
{% load static %}
<div>
    <br>
    <br>
    <br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.SchoolShopping.com 2020</p>
    </div>
</footer>

templates/header.html
{# 定义导航栏 #}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        {# 导航栏商标 #}
        <a href="#" class="navbar-brand">校园小商品交易平台</a>
        {# 导航入口 #}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'publisher:publisher_list' %}" class="nav-link">商品列表</a>
            </li>
            <!-- Django的 if 模板语句 -->
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'publisher:publisher_create' %}" class="nav-link">发布商品</a>
                </li>
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                        <a href="{% url 'userprofile:update_password' %}" class="dropdown-item">修改密码</a>
                        <a href="#" onclick="user_delete()" class="dropdown-item">删除用户</a>
                        <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示 “登录” -->
            {% else %}
                <li class="nav-item">
                    <a href="#" onclick="confirm_publish()" class="nav-link">发布商品</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                </li>
                <!-- if 语句在这里结束 -->
            {% endif %}
        </ul>
    </div>
    {% if user.is_authenticated %}
        <form action="{% url 'userprofile:delete' user.id %}" method="post" id="user_delete" style="display: none">
            {% csrf_token %}
            <button type="submit">发送</button>
        </form>
        <script>
            function user_delete() {
                layer.open({
                    title: '删除用户',
                    content: '确认删除用户资料吗？',
                    yes: function (index) {
                        $('form#user_delete button').click()
                        layer.close(index);
                    },
                })
            }
        </script>
    {% endif %}
    <script>
        function confirm_publish() {
            // 调用layer弹窗组件
            layer.open({
                // 弹窗标题
                title: "发布商品",
                // 正文
                content: "请先登录",
                // 点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    // 指定应当前往的 url
                    location.href = '{% url "userprofile:login" %}'
                },
            })
        }
    </script>
</nav>